# Change these first
owner: Danrrodrigues # Your GitHub organization or username, where this repository lives
repo: site-monitor # The name of this repository

sites:
  - name: Angélica Andrade - Site Principal
    url: https://www.angelicaandrade.com.br
  - name: Angélica Andrade - Blog
    url: https://www.angelicaandrade.com.br/blog

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /site-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - Angélica Andrade
  introTitle: "**Monitor de Status** do site Angélica Andrade"
  introMessage: Esta página mostra o status em tempo real do site e seus serviços. Monitoramento automatizado a cada 5 minutos.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Site Principal
      href: https://www.angelicaandrade.com.br

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
